name: "terraform"

on:
  workflow_dispatch:

jobs:
  init:
    defaults:
      run:
        shell: "bash"
    environment:
      name: "development"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: "hashicorp/setup-terraform@v2"
      - run: "terraform workspaces new ${{ environment.name }}"
      - run: "terraform workspaces select ${{ environment.name }}"
      - run: "terraform init -upgrade"
      - run: "terraform plan -input=false"
